# Generated by Django 4.1.4 on 2023-01-03 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0002_alter_address_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Situação',
                'verbose_name_plural': 'Situações',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('release_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano de lançamento')),
                ('manufacture_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano de fabricação')),
                ('specifications', models.TextField(blank=True, null=True, verbose_name='Especificações')),
                ('damages', models.TextField(blank=True, null=True, verbose_name='Avarias')),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de mercado')),
                ('sale_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de venda')),
                ('original', models.BooleanField(default=True, verbose_name='É original')),
                ('box', models.BooleanField(default=True, verbose_name='Tem caixa')),
                ('original_box', models.BooleanField(default=True, verbose_name='Caixa original')),
                ('negotiable', models.BooleanField(default=True, verbose_name='É negociável')),
                ('registration_date', models.DateField(auto_now=True, verbose_name='Data de cadastro')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('photo1', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Foto 1')),
                ('photo2', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Foto 2')),
                ('photo3', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Foto 3')),
                ('photo4', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Foto 4')),
                ('photo5', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Foto 5')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.collection', verbose_name='Coleção')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.group', verbose_name='Grupo')),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.situation', verbose_name='Situação')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
        ),
    ]
