# Generated by Django 4.1.4 on 2023-01-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='identifier_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código identificador'),
        ),
    ]
