# Generated by Django 4.1.4 on 2023-01-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d', verbose_name='Foto 1'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d', verbose_name='Foto 2'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d', verbose_name='Foto 3'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d', verbose_name='Foto 4'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d', verbose_name='Foto 5'),
        ),
    ]
