# Generated by Django 4.1.4 on 2023-01-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_item_photo1_alter_item_photo2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='situation',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
    ]
