# Generated by Django 4.1.4 on 2023-01-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_item_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='x', max_length=255, verbose_name='Descrição'),
            preserve_default=False,
        ),
    ]
