# Generated by Django 4.1.4 on 2023-01-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='developer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Desenvolvedor'),
        ),
        migrations.AddField(
            model_name='item',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de série'),
        ),
    ]
