# Generated by Django 4.1.4 on 2023-01-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_developer_item_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='distributor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Distribuidor'),
        ),
    ]
