# Generated by Django 4.1.4 on 2023-01-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_item_last_update_date_alter_item_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='last_update_date',
            field=models.DateTimeField(verbose_name='Data da última atualização'),
        ),
        migrations.AlterField(
            model_name='item',
            name='registration_date',
            field=models.DateTimeField(verbose_name='Data de cadastro'),
        ),
    ]
