# Generated by Django 4.1.4 on 2023-01-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_alter_item_last_update_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='last_update_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da última atualização'),
        ),
        migrations.AlterField(
            model_name='item',
            name='registration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de cadastro'),
        ),
    ]
