# Generated by Django 4.1.4 on 2023-01-22 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_alter_item_last_update_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='last_update_date',
        ),
    ]
