# Generated by Django 4.1.4 on 2023-01-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_remove_item_last_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='last_update_date',
            field=models.DateTimeField(default='2023-01-21 00:00:00+00', editable=False, verbose_name='Data da última atualização'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='registration_date',
            field=models.DateTimeField(default='2023-01-21 00:00:00+00', editable=False, verbose_name='Data de cadastro'),
            preserve_default=False,
        ),
    ]
