# Generated by Django 4.1.4 on 2023-01-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_item_last_update_date_alter_item_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='composition',
            field=models.TextField(blank=True, null=True, verbose_name='Composição'),
        ),
    ]
