# Generated by Django 4.1.4 on 2023-01-22 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_item_composition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='photo5',
        ),
    ]
