# Generated by Django 4.1.4 on 2023-01-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='specifications',
            field=models.TextField(blank=True, null=True, verbose_name='Especificações'),
        ),
    ]
