# Generated by Django 4.1.4 on 2023-01-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adr_zipcode', models.CharField(max_length=8, verbose_name='Cep')),
                ('adr_address', models.CharField(max_length=50, verbose_name='Endereço')),
                ('adr_number', models.CharField(max_length=5, verbose_name='Número')),
                ('adr_complement', models.CharField(blank=True, max_length=30, null=True, verbose_name='Complemento')),
                ('adr_district', models.CharField(max_length=30, verbose_name='Bairro')),
                ('adr_city', models.CharField(max_length=30, verbose_name='Município')),
                ('adr_country', models.CharField(max_length=30, verbose_name='País')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
    ]
